# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anapencere.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(170, 30, 791, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.baslik_label = QtWidgets.QLabel(self.frame)
        self.baslik_label.setGeometry(QtCore.QRect(160, 20, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(17)
        self.baslik_label.setFont(font)
        self.baslik_label.setAlignment(QtCore.Qt.AlignCenter)
        self.baslik_label.setObjectName("baslik_label")
        self.arama_yap_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.arama_yap_line_edit.setGeometry(QtCore.QRect(180, 160, 741, 20))
        self.arama_yap_line_edit.setObjectName("arama_yap_line_edit")
        self.bilgi_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.bilgi_tableWidget.setGeometry(QtCore.QRect(30, 210, 1091, 281))
        self.bilgi_tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bilgi_tableWidget.setShowGrid(False)
        self.bilgi_tableWidget.setObjectName("bilgi_tableWidget")
        self.bilgi_tableWidget.setColumnCount(9)
        self.bilgi_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.bilgi_tableWidget.setHorizontalHeaderItem(8, item)
        self.bilgi_tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.bilgi_tableWidget.horizontalHeader().setStretchLastSection(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 21))
        self.menubar.setObjectName("menubar")
        self.kitap_duzenleme_menu = QtWidgets.QMenu(self.menubar)
        self.kitap_duzenleme_menu.setObjectName("kitap_duzenleme_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionKitap_D_zenleme_Sayfas = QtWidgets.QAction(MainWindow)
        self.actionKitap_D_zenleme_Sayfas.setObjectName("actionKitap_D_zenleme_Sayfas")
        self.proje_ekleme_sayfa = QtWidgets.QAction(MainWindow)
        self.proje_ekleme_sayfa.setObjectName("proje_ekleme_sayfa")
        self.kitap_duzenleme_menu.addSeparator()
        self.kitap_duzenleme_menu.addAction(self.proje_ekleme_sayfa)
        self.menubar.addAction(self.kitap_duzenleme_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.baslik_label.setText(_translate("MainWindow", "İŞ TAKİP VE YÖNETİM SİSTEMİ"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Proje Adı"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Proje Sorumlusu"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Çalışan İşçi Sayısı"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Proje Durumu"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Maliyet"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Şirket"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Proje Başlangıç Tarihi"))
        item = self.bilgi_tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Proje Bitiş Tarihi"))
        self.kitap_duzenleme_menu.setTitle(_translate("MainWindow", "Seçenekler"))
        self.actionKitap_D_zenleme_Sayfas.setText(_translate("MainWindow", "Kitap DÜzenleme  Sayfası"))
        self.proje_ekleme_sayfa.setText(_translate("MainWindow", "Proje Ekleme"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
